name: Development Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: develop
      - name: Install Dependencies
        run: npm install
      - name: Build 
        run: npm run build
      - name: Deploy to Development
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
            FIREBASE_TOKEN: ${{ secrets.firebase }}
